import "../styles/style.css";
import Header from "@/components/Header";
import Image from "next/image";
import bgPokeball from "../assets/images/bgPokeball.svg";
export const metadata = {
  title: "Pokemon App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-50">
        <div className="relative">
          <Image
            src={bgPokeball}
            alt="pokeball"
            className="absolute left-0 right-0 -top-40 bottom-0 mx-auto -z-10 w-full sm:w-1/2 md:w-1/3"
          />
        </div>
        <Header />
        {children}
      </body>
    </html>
  );
}
